# ==============================================================================
# RideHub Multi-VPS Inventory (Simulation & Production Ready)
# ==============================================================================

[vps_infra]
# Node 1: Chạy Cụm Hạ Tầng Trung Tâm (Keycloak, Kafka, Consul, Vault, Redis, Observability)
vps1 ansible_host=127.0.0.1 ansible_port=2221 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519 internal_ip=172.28.0.10

[vps_microservices]
# Node 2: Chạy Cụm Microservices Nghiệp Vụ (API Gateway, ms_booking, ms_user, ms_route, DBs)
vps2 ansible_host=127.0.0.1 ansible_port=2222 ansible_user=root ansible_ssh_private_key_file=~/.ssh/id_ed25519 internal_ip=172.28.0.20

[all_vps:children]
vps_infra
vps_microservices
